### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by wang316902972** [HbnKing/Flume-ng-Database#10]
无数据的情况下轮询几秒后轮询速度会加快，然后内存溢出
20/02/12 04:27:34 ERROR source.SQLSource: RDB  process error ,error is java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "PollableSourceRunner-SQLSource-r1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:669)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "PollableSourceRunner-SQLSource-r1"

**Comment by HbnKing** [comment]
好的 我再看一下

**Comment by HbnKing** [comment]
@wang316902972 
#每次 吐出量 与 内存有关
a1.sources.r1.batchsize = 128

调整这个参数试试

**Comment by wang316902972** [comment]
我是把&nbsp;getBackOffSleepIncrement getMaxBackOffSleepInterval&nbsp; 这两参数设置为0，在process处理完返回状态之后sleep一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hbn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午4:14
收件人:&nbsp;"HbnKing/Flume-ng-Database"<Flume-ng-Database@noreply.github.com&gt;;
抄送:&nbsp;"316902972"<316902972@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [HbnKing/Flume-ng-Database] 内存溢出 (#10)




@wang316902972
 #每次 吐出量 与 内存有关
 a1.sources.r1.batchsize = 128
 
调整这个参数试试

**Comment by HbnKing** [comment]
也是种思路 。这两个参数 晚点 配到外面吧

**Comment by HbnKing** [comment]
大佬有没有兴趣修复一下
